### ISSUE TITLE
フルスクリーンに対応する

### ISSUE THREAD

**Issue by yugu0202** [UDHI-LAB/MTCSync#19]
実運用上ではフルスクリーン表示で起動するのでフルスクリーンで起動できるようにする

**Comment by yugu0202** [comment]
@noko1024 
ヒューマンエラー的にはキーでのフルスクリーンの切り替えはしたくないが, スクリーンの位置の取得が難しくカレントディスプレイでしかフルスクリーンが表示できないため, 泣く泣くキーバインドによるトグルにしているんだけどどんな方法がいいと思う？

**Comment by yugu0202** [comment]
参考文献
https://mpv.io/manual/master/#options-fs-screen

**Comment by noko1024** [comment]
暗転状態(任意の画像を表示して)起動
スクリーン位置合わせが限界な気がする

**Comment by yugu0202** [comment]
ウィンドウモードのままってこと？

**Comment by noko1024** [comment]
任意のスクリーンまで動かしてから全画面に切り替えるとそのスクリーン上で全画面になるとかない？

**Comment by yugu0202** [comment]
なるからトグルにしているんだけど、mpvにキーインプットが向いているときに間違って押しちゃったらウィンドウモードに戻っちゃうからそれを止めたいとかあればっていう感じの質問
さらにロックキー的なの用意する？

**Comment by yugu0202** [comment]
F11キーでのトグルに変更しビルトインのキーバインドを廃止
